# =============================================================================
# Amazon FPGA Hardware Development Kit
#
# Copyright 2024 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License"). You may not use
# this file except in compliance with the License. A copy of the License is
# located at
#
#    http://aws.amazon.com/asl/
#
# or in the "license" file accompanying this file. This file is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or
# implied. See the License for the specific language governing permissions and
# limitations under the License.
# =============================================================================


# Adds an easy make target that sets $TEST and runs the all (compile & run) target
single_register_read_write_base_test: TEST=single_register_read_write_base_test
single_register_read_write_base_test: all

# Add additional tests here that are located in the $CL_DIR/verif/tests directory
# module_name_of_new_test: TEST=module_name_of_new_test
# module_name_of_new_test: all

hardware_test: TEST=hardware_test
hardware_test: all

test_simple_register_c: TEST=test_simple_register_c
test_simple_register_c: C_TEST=test_simple_register_c
test_simple_register_c: all